#!/usr/bin/env python3
"""Step 4b: Train DiT Flow Policy for Isaac Lab Pick-Place using LeRobot.

This script trains a vision-based DiT Flow Policy (Diffusion Transformer with
Flow Matching) on the forward trajectory data generated by script 3, using the
same NPZ data format as 4_train_diffusion.py.

DiT Flow uses:
- Transformer architecture instead of U-Net (better scaling)
- Flow Matching objective instead of DDPM (faster inference, ~100 steps)
- AdaLN-Zero conditioning for time step (more stable training)

=============================================================================
DEPENDENCIES
=============================================================================
Requires lerobot_policy_ditflow (installed from source):
    pip install -e ./lerobot_policy_ditflow

=============================================================================
INPUT DATA FORMAT (same as 4_train_diffusion.py)
=============================================================================
NPZ file with episodes list, each dict containing:
    - obs:           (T, 36)  State observations
    - images:        (T, H, W, 3)  RGB images from table camera (uint8)
    - wrist_images:  (T, H, W, 3)  RGB images from wrist camera (uint8)
    - ee_pose:       (T, 7)   EE poses [x, y, z, qw, qx, qy, qz]
    - obj_pose:      (T, 7)   Object poses
    - action:        (T, 8)   Goal actions [ee_pose, gripper]

=============================================================================
OBSERVATION STATE DIMENSION OPTIONS
=============================================================================
  Flags                                    | state_dim | Components
  -----------------------------------------|-----------|---------------------------
  (none)                                   |     7     | ee_pose(7)
  --include_gripper                        |     8     | ee_pose(7) + gripper(1)
  --include_obj_pose                       |    14     | ee_pose(7) + obj_pose(7)
  --include_obj_pose --include_gripper     |    15     | ee_pose(7) + obj_pose(7) + gripper(1)

=============================================================================
USAGE EXAMPLES
=============================================================================
# Single GPU training
CUDA_VISIBLE_DEVICES=0 python scripts/scripts_pick_place/4_train_ditflow.py \
    --dataset data/A_pick_place.npz \
    --out runs/ditflow_PP_A_circle \
    --batch_size 32 --steps 50000 \
    --include_obj_pose --include_gripper --wandb

# Multi-GPU training
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 \
    scripts/scripts_pick_place/4_train_ditflow.py \
    --dataset data/A_pick_place.npz \
    --out runs/ditflow_PP_A_circle \
    --batch_size 32 --steps 50000 \
    --include_obj_pose --include_gripper --wandb

# Resume training (DAgger iteration)
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 \
    scripts/scripts_pick_place/4_train_ditflow.py \
    --dataset dummy.npz \
    --lerobot_dataset_dir runs/ditflow_PP_A/lerobot_dataset \
    --out runs/ditflow_PP_A \
    --steps 10000 --batch_size 32 \
    --n_action_steps 16 \
    --skip_convert --resume \
    --include_obj_pose --include_gripper --wandb
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path

import numpy as np
import torch

# Suppress verbose output from video encoders
os.environ["AV_LOG_LEVEL"] = "quiet"
os.environ["SVT_LOG"] = "0"
os.environ["FFMPEG_LOG_LEVEL"] = "quiet"

# Reuse data loading/conversion from 4_train_diffusion.py
import importlib.util as _importlib_util

_diffusion_spec = _importlib_util.spec_from_file_location(
    "train_diffusion",
    str(Path(__file__).parent / "4_train_diffusion.py"),
)
_diffusion_mod = _importlib_util.module_from_spec(_diffusion_spec)
_diffusion_spec.loader.exec_module(_diffusion_mod)

load_episodes_from_npz = _diffusion_mod.load_episodes_from_npz
convert_npz_to_lerobot_format = _diffusion_mod.convert_npz_to_lerobot_format


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Train DiT Flow Policy for Isaac Lab Pick-Place.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # =========================================================================
    # Input/Output Arguments
    # =========================================================================
    parser.add_argument("--dataset", type=str, default="data/B_goal_actions_latest.npz",
                        help="Path to the goal-action dataset NPZ file.")
    parser.add_argument("--out", type=str, default="runs/ditflow_PP_B",
                        help="Output directory for saving model checkpoints and logs.")
    parser.add_argument("--lerobot_dataset_dir", type=str, default=None,
                        help="Directory for the converted LeRobot dataset. Default: {out}/lerobot_dataset.")

    # =========================================================================
    # Mode Selection
    # =========================================================================
    parser.add_argument("--convert_only", action="store_true",
                        help="Only convert data to LeRobot format, don't train.")
    parser.add_argument("--skip_convert", action="store_true",
                        help="Skip data conversion (assume already converted).")
    parser.add_argument("--force_convert", action="store_true",
                        help="Force re-conversion even if dataset exists.")
    parser.add_argument("--include_obj_pose", action="store_true",
                        help="Include object pose (7D) in observation.state.")
    parser.add_argument("--include_gripper", action="store_true",
                        help="Include gripper state (1D) in observation.state.")

    # =========================================================================
    # Training Hyperparameters
    # =========================================================================
    parser.add_argument("--num_episodes", type=int, default=-1,
                        help="Number of episodes to use. -1 = all.")
    parser.add_argument("--steps", type=int, default=100000,
                        help="Number of training steps.")
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--fps", type=int, default=20)

    # =========================================================================
    # DiT Flow Policy Architecture
    # =========================================================================
    parser.add_argument("--n_obs_steps", type=int, default=2)
    parser.add_argument("--horizon", type=int, default=16)
    parser.add_argument("--n_action_steps", type=int, default=8)
    parser.add_argument("--vision_backbone", type=str, default="resnet18")
    parser.add_argument("--crop_shape", type=int, nargs=2, default=[128, 128],
                        help="Image crop shape (H, W). Default: 128 128.")
    parser.add_argument("--pretrained_backbone_weights", type=str, default=None)
    parser.add_argument("--num_inference_steps", type=int, default=100)
    parser.add_argument("--hidden_dim", type=int, default=512)
    parser.add_argument("--num_blocks", type=int, default=6)
    parser.add_argument("--num_heads", type=int, default=16)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--dim_feedforward", type=int, default=4096)
    parser.add_argument("--training_noise_sampling", type=str, default="uniform",
                        choices=["uniform", "beta"])
    parser.add_argument("--clip_sample", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--clip_sample_range", type=float, default=1.0)

    # =========================================================================
    # Logging and Checkpointing
    # =========================================================================
    parser.add_argument("--log_freq", type=int, default=50)
    parser.add_argument("--save_freq", type=int, default=20000)
    parser.add_argument("--resume", action="store_true",
                        help="Resume training from checkpoint.")
    parser.add_argument("--overwrite", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--sample_weights", type=str, default=None,
                        help="Path to sampling_weights.json for weighted sampling.")
    parser.add_argument("--viz_save_freq", type=int, default=20000)
    parser.add_argument("--enable_xyz_viz", action="store_true")

    # =========================================================================
    # Overfit Mode
    # =========================================================================
    parser.add_argument("--overfit", action="store_true")

    # =========================================================================
    # Device / WandB / Validation
    # =========================================================================
    parser.add_argument("--device", type=str, default=None)
    parser.add_argument("--wandb", action="store_true")
    parser.add_argument("--wandb_project", type=str, default="rev2fwd-ditflow-pick-place")
    parser.add_argument("--val_split", type=float, default=0.0)
    parser.add_argument("--val_freq", type=int, default=500)

    # =========================================================================
    # Finetune from external checkpoint (not resume)
    # =========================================================================
    parser.add_argument("--finetune", action="store_true",
                        help="Load pretrained weights but start training from step 0.")

    return parser.parse_args()


def train_with_lerobot_api(
    args: argparse.Namespace,
    lerobot_dataset_dir: Path,
    image_height: int,
    image_width: int,
    has_wrist: bool = False,
    include_obj_pose: bool = False,
    include_gripper: bool = False,
    overfit_env_init: dict | None = None,
    train_episodes: list[int] | None = None,
    val_episodes: list[int] | None = None,
    state_slice_end: int | None = None,
) -> dict:
    """Train DiT Flow using LeRobot's Python API."""
    # Register third-party plugins (imports lerobot_policy_ditflow)
    from lerobot.utils.import_utils import register_third_party_plugins
    register_third_party_plugins()

    from lerobot_policy_ditflow import DiTFlowConfig

    from lerobot.configs.default import DatasetConfig, WandBConfig
    from lerobot.configs.train import TrainPipelineConfig
    from lerobot.configs.types import FeatureType, PolicyFeature
    from lerobot.scripts.lerobot_train import train
    from rev2fwd_il.train.lerobot_train_with_viz import train_with_xyz_visualization

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    is_main_process = True
    if "LOCAL_RANK" in os.environ:
        local_rank = int(os.environ["LOCAL_RANK"])
        is_main_process = (local_rank == 0)

    # Handle overwrite
    checkpoint_dir = out_dir / "checkpoints"
    if is_main_process and args.overwrite and checkpoint_dir.exists() and not args.resume and not getattr(args, 'finetune', False):
        print(f"Removing existing checkpoints directory: {checkpoint_dir}")
        shutil.rmtree(checkpoint_dir)

    if is_main_process and args.overfit and overfit_env_init is not None:
        overfit_init_path = out_dir / "overfit_env_init.json"
        with open(overfit_init_path, "w") as f:
            json.dump(overfit_env_init, f, indent=2)
        print(f"[Overfit Mode] Saved env init params to: {overfit_init_path}")

    if torch.distributed.is_initialized():
        torch.distributed.barrier()

    device = args.device
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    # State dimension (same as diffusion policy)
    state_dim = 7  # base: ee_pose (7) quaternion
    if include_obj_pose:
        state_dim += 7
    if include_gripper:
        state_dim += 1

    # Configure features
    input_features = {
        "observation.image": PolicyFeature(
            type=FeatureType.VISUAL,
            shape=(3, image_height, image_width),
        ),
        "observation.state": PolicyFeature(
            type=FeatureType.STATE,
            shape=(state_dim,),
        ),
    }
    if has_wrist:
        input_features["observation.wrist_image"] = PolicyFeature(
            type=FeatureType.VISUAL,
            shape=(3, image_height, image_width),
        )

    output_features = {
        "action": PolicyFeature(
            type=FeatureType.ACTION,
            shape=(8,),  # goal ee_pose (7) + gripper (1) — same as diffusion
        ),
    }

    # Dynamically calculate drop_n_last_frames
    drop_n_last_frames = args.horizon - args.n_action_steps - args.n_obs_steps + 1
    if drop_n_last_frames < 0:
        print(f"Warning: drop_n_last_frames would be {drop_n_last_frames}, clamping to 0.")
        drop_n_last_frames = 0

    # Create DiT Flow Policy configuration
    policy_cfg = DiTFlowConfig(
        n_obs_steps=args.n_obs_steps,
        horizon=args.horizon,
        n_action_steps=args.n_action_steps,
        input_features=input_features,
        output_features=output_features,
        vision_backbone=args.vision_backbone,
        crop_shape=tuple(args.crop_shape),
        pretrained_backbone_weights=args.pretrained_backbone_weights,
        device=device,
        push_to_hub=False,
        # DiT-specific parameters
        hidden_dim=args.hidden_dim,
        num_blocks=args.num_blocks,
        num_heads=args.num_heads,
        dropout=args.dropout,
        dim_feedforward=args.dim_feedforward,
        num_inference_steps=args.num_inference_steps,
        training_noise_sampling=args.training_noise_sampling,
        clip_sample=args.clip_sample,
        clip_sample_range=args.clip_sample_range,
        drop_n_last_frames=drop_n_last_frames,
        optimizer_lr=args.lr,
    )

    # Print normalization settings
    print("\n" + "=" * 60)
    print("[DEBUG] TRAINING Normalization Settings")
    print("=" * 60)
    print(f"  policy_cfg.normalization_mapping:")
    for feat_type, norm_mode in policy_cfg.normalization_mapping.items():
        print(f"    {feat_type}: {norm_mode}")
    print("=" * 60 + "\n")

    # Create dataset configuration
    dataset_cfg = DatasetConfig(
        repo_id="local/rev2fwd_ditflow",
        root=str(lerobot_dataset_dir),
        episodes=train_episodes,
    )

    val_dataset_cfg = None
    if val_episodes is not None and len(val_episodes) > 0:
        val_dataset_cfg = DatasetConfig(
            repo_id="local/rev2fwd_ditflow",
            root=str(lerobot_dataset_dir),
            episodes=val_episodes,
        )

    wandb_cfg = WandBConfig(
        enable=args.wandb,
        project=args.wandb_project,
        run_id=None,
        mode=None,
    )

    checkpoint_dir = out_dir / "checkpoints"
    resume_config_path = None

    if args.resume:
        checkpoints_subdir = checkpoint_dir / "checkpoints"
        if not checkpoints_subdir.exists():
            raise FileNotFoundError(f"Cannot resume: {checkpoints_subdir} does not exist.")
        checkpoint_dirs = [d for d in checkpoints_subdir.iterdir() if d.is_dir()]
        if not checkpoint_dirs:
            raise FileNotFoundError(f"Cannot resume: no checkpoints found in {checkpoints_subdir}.")

        last_checkpoint = checkpoints_subdir / "last"
        if last_checkpoint.exists() and last_checkpoint.is_dir():
            latest_checkpoint = last_checkpoint
        else:
            numeric_dirs = [(int(d.name), d) for d in checkpoint_dirs if d.name.isdigit()]
            if numeric_dirs:
                numeric_dirs.sort(key=lambda x: x[0])
                latest_checkpoint = numeric_dirs[-1][1]
            else:
                latest_checkpoint = sorted(checkpoint_dirs, key=lambda x: x.name)[-1]

        print(f"Resuming from checkpoint: {latest_checkpoint}")
        resume_config_path = latest_checkpoint / "pretrained_model" / "train_config.json"
        if not resume_config_path.exists():
            raise FileNotFoundError(f"Cannot resume: train_config.json not found at {resume_config_path}")

        train_cfg = TrainPipelineConfig.from_pretrained(str(resume_config_path.parent))
        train_cfg.resume = True
        train_cfg.steps = args.steps
        train_cfg.wandb = wandb_cfg
        train_cfg.checkpoint_path = latest_checkpoint
        train_cfg.policy.pretrained_path = latest_checkpoint / "pretrained_model"
        train_cfg.dataset.root = str(lerobot_dataset_dir)
        train_cfg.output_dir = checkpoint_dir

        print(f"  Will continue training to step {args.steps}")
        print(f"  Dataset root updated to: {lerobot_dataset_dir}")
    else:
        train_cfg = TrainPipelineConfig(
            dataset=dataset_cfg,
            policy=policy_cfg,
            output_dir=checkpoint_dir,
            seed=args.seed,
            num_workers=args.num_workers,
            batch_size=args.batch_size,
            steps=args.steps,
            log_freq=args.log_freq,
            save_freq=args.save_freq,
            save_checkpoint=True,
            wandb=wandb_cfg,
            resume=False,
            eval_freq=0,
        )

    # Print training info
    print("\n" + "=" * 60)
    print("Starting DiT Flow Policy Training (Simulator Pick-Place)")
    print("=" * 60)
    print(f"  Dataset: {args.dataset}")
    print(f"  LeRobot dataset: {lerobot_dataset_dir}")
    print(f"  Output: {checkpoint_dir}")
    print(f"  Steps: {args.steps}")
    print(f"  Batch size: {args.batch_size}")
    print(f"  Learning rate: {args.lr}")
    print(f"  Image shape: ({image_height}, {image_width})")
    print(f"  Has wrist camera: {has_wrist}")
    print(f"  Include obj_pose: {include_obj_pose}")
    print(f"  Include gripper: {include_gripper}")
    print(f"  State dim: {state_dim}")
    print(f"  Action dim: 8 (goal ee_pose + gripper)")
    print(f"  Crop shape: {tuple(args.crop_shape)}")
    print(f"  Horizon: {args.horizon}")
    print(f"  N obs steps: {args.n_obs_steps}")
    print(f"  N action steps: {args.n_action_steps}")
    print(f"  Vision backbone: {args.vision_backbone}")
    print(f"  Device: {device}")
    print(f"  WandB: {args.wandb}")
    print("")
    print("  DiT-specific parameters:")
    print(f"    Hidden dim: {args.hidden_dim}")
    print(f"    Num blocks: {args.num_blocks}")
    print(f"    Num heads: {args.num_heads}")
    print(f"    Dropout: {args.dropout}")
    print(f"    Feedforward dim: {args.dim_feedforward}")
    print(f"    Inference steps: {args.num_inference_steps}")
    print(f"    Noise sampling: {args.training_noise_sampling}")
    print(f"    Clip sample: {args.clip_sample} (range: {args.clip_sample_range})")
    print(f"    Drop N last frames: {drop_n_last_frames}")
    if train_episodes is not None:
        print(f"  Train episodes: {len(train_episodes)}")
    if val_episodes is not None:
        print(f"  Val episodes: {len(val_episodes)}")
    print("=" * 60 + "\n")

    # Run training
    original_argv = sys.argv.copy()
    if resume_config_path is not None:
        sys.argv = [sys.argv[0], f"--config_path={resume_config_path}"]

    sample_weights_path = getattr(args, 'sample_weights', None)

    try:
        if args.enable_xyz_viz:
            xyz_viz_dir = out_dir / "xyz_viz"
            train_with_xyz_visualization(
                train_cfg,
                viz_save_freq=args.viz_save_freq,
                xyz_viz_dir=xyz_viz_dir,
                val_dataset_cfg=val_dataset_cfg,
                val_freq=args.val_freq,
                state_slice_end=state_slice_end,
                sample_weights_path=sample_weights_path,
            )
        else:
            if state_slice_end is not None or sample_weights_path is not None:
                train_with_xyz_visualization(
                    train_cfg,
                    viz_save_freq=0,
                    xyz_viz_dir=None,
                    val_dataset_cfg=val_dataset_cfg,
                    val_freq=args.val_freq,
                    state_slice_end=state_slice_end,
                    sample_weights_path=sample_weights_path,
                )
            else:
                train(train_cfg)
    finally:
        sys.argv = original_argv

    return {
        "output_dir": str(checkpoint_dir),
        "steps": args.steps,
    }


def main() -> None:
    """Main entry point."""
    args = _parse_args()

    if args.overfit:
        if args.num_episodes != 1:
            print(f"\n[Overfit Mode] Setting num_episodes=1 (was {args.num_episodes})")
            args.num_episodes = 1
        out_dir_temp = Path(args.out)
        overfit_init_path = out_dir_temp / "overfit_env_init.json"
        lerobot_dataset_dir_temp = args.lerobot_dataset_dir
        if lerobot_dataset_dir_temp is None:
            lerobot_dataset_dir_temp = out_dir_temp / "lerobot_dataset"
        lerobot_dataset_dir_temp = Path(lerobot_dataset_dir_temp)

        if overfit_init_path.exists() and lerobot_dataset_dir_temp.exists():
            print(f"[Overfit Mode] Found existing data, skipping re-conversion")
        elif not args.force_convert:
            print("[Overfit Mode] Enabling force_convert to extract env init params")
            args.force_convert = True

    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)

    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    world_size = int(os.environ.get("WORLD_SIZE", 1))
    is_main_process = (local_rank == 0)

    if world_size > 1 and not torch.distributed.is_initialized():
        torch.distributed.init_process_group(backend="nccl")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    lerobot_dataset_dir = args.lerobot_dataset_dir
    if lerobot_dataset_dir is None:
        lerobot_dataset_dir = out_dir / "lerobot_dataset"
    lerobot_dataset_dir = Path(lerobot_dataset_dir)

    overfit_env_init = None

    # Step 1: Convert data to LeRobot format (reuse from 4_train_diffusion.py)
    if not args.skip_convert:
        if is_main_process:
            image_height, image_width, has_wrist, overfit_env_init = convert_npz_to_lerobot_format(
                npz_path=args.dataset,
                output_dir=lerobot_dataset_dir,
                fps=args.fps,
                repo_id="local/rev2fwd_ditflow",
                force=args.force_convert,
                num_episodes=args.num_episodes,
                include_obj_pose=args.include_obj_pose,
                include_gripper=args.include_gripper,
                overfit=args.overfit,
            )
            meta_file = out_dir / ".conversion_meta.json"
            meta_data = {
                "image_height": image_height,
                "image_width": image_width,
                "has_wrist": has_wrist,
                "include_obj_pose": args.include_obj_pose,
                "include_gripper": args.include_gripper,
                "overfit_env_init": overfit_env_init,
            }
            with open(meta_file, "w") as f:
                json.dump(meta_data, f, indent=2)

        if torch.distributed.is_initialized():
            torch.distributed.barrier()

        if not is_main_process:
            meta_file = out_dir / ".conversion_meta.json"
            with open(meta_file, "r") as f:
                meta = json.load(f)
            image_height = meta["image_height"]
            image_width = meta["image_width"]
            has_wrist = meta["has_wrist"]
            overfit_env_init = meta.get("overfit_env_init", None)
    else:
        meta_path = lerobot_dataset_dir / "meta" / "info.json"
        if meta_path.exists():
            print(f"[Skip Convert] Reading config from existing LeRobot dataset: {lerobot_dataset_dir}")
            with open(meta_path, "r") as f:
                info = json.load(f)
            features = info.get("features", {})

            if "observation.image" in features:
                img_shape = features["observation.image"]["shape"]
                image_height = img_shape[1]
                image_width = img_shape[2]
            else:
                raise ValueError("observation.image not found in dataset features")

            has_wrist = "observation.wrist_image" in features

            print(f"  Image size: {image_height}x{image_width}")
            print(f"  Has wrist camera: {has_wrist}")
            print(f"  Total episodes: {info.get('total_episodes', 'unknown')}")
            print(f"  Total frames: {info.get('total_frames', 'unknown')}")
        else:
            print(f"[Skip Convert] LeRobot dataset not found, loading NPZ: {args.dataset}")
            episodes = load_episodes_from_npz(args.dataset, num_episodes=args.num_episodes)
            image_shape = episodes[0]["images"].shape[1:]
            image_height, image_width = image_shape[0], image_shape[1]
            has_wrist = "wrist_images" in episodes[0]

    if args.convert_only:
        if is_main_process:
            print("Data conversion complete. Exiting (--convert_only flag).")
        return

    # Check if state slicing is needed
    meta_path = lerobot_dataset_dir / "meta" / "info.json"
    dataset_state_dim = None
    if meta_path.exists():
        with open(meta_path, "r") as f:
            info = json.load(f)
        features = info.get("features", {})
        if "observation.state" in features:
            dataset_state_dim = features["observation.state"]["shape"][0]

    policy_state_dim = 7
    if args.include_obj_pose:
        policy_state_dim += 7
    if args.include_gripper:
        policy_state_dim += 1

    state_slice_end = None
    if dataset_state_dim is not None and policy_state_dim < dataset_state_dim:
        state_slice_end = policy_state_dim
        if is_main_process:
            print(f"\n[State Slicing] Dataset state_dim={dataset_state_dim}, "
                  f"policy state_dim={policy_state_dim}, slicing to [:{state_slice_end}]")
    elif dataset_state_dim is not None and policy_state_dim > dataset_state_dim:
        raise ValueError(
            f"Policy state_dim ({policy_state_dim}) > dataset state_dim ({dataset_state_dim})."
        )

    # Compute train/val split
    train_episodes = None
    val_episodes = None

    if args.val_split > 0.0:
        meta_path = lerobot_dataset_dir / "meta" / "info.json"
        if meta_path.exists():
            with open(meta_path, "r") as f:
                info = json.load(f)
            total_episodes = info.get("total_episodes", 0)
        else:
            total_episodes = 0

        if total_episodes > 0:
            all_episode_indices = list(range(total_episodes))
            rng = np.random.default_rng(args.seed)
            rng.shuffle(all_episode_indices)

            n_val = max(1, int(total_episodes * args.val_split))
            val_episodes = sorted(all_episode_indices[:n_val])
            train_episodes = sorted(all_episode_indices[n_val:])

            if is_main_process:
                print(f"\n[Train/Val Split] Total={total_episodes}, "
                      f"Train={len(train_episodes)}, Val={len(val_episodes)}")

    # Step 2: Train
    result = train_with_lerobot_api(
        args=args,
        lerobot_dataset_dir=lerobot_dataset_dir,
        image_height=image_height,
        image_width=image_width,
        has_wrist=has_wrist,
        include_obj_pose=args.include_obj_pose,
        include_gripper=args.include_gripper,
        overfit_env_init=overfit_env_init,
        train_episodes=train_episodes,
        val_episodes=val_episodes,
        state_slice_end=state_slice_end,
    )

    print("\n" + "=" * 60)
    print("Training Complete!")
    print("=" * 60)
    print(f"  Output directory: {result['output_dir']}")
    print(f"  Total steps: {result['steps']}")
    print(f"  Policy type: DiT Flow (Diffusion Transformer + Flow Matching)")
    print("=" * 60)


if __name__ == "__main__":
    main()
